// packages/core/index.js

import { TokenParser }      from './parser.js'
import { UtilityGenerator } from './utility-generator.js'
import { PatternExpander }  from './pattern-expander.js'
import { VariantGenerator } from './variant-generator.js'
import { TypesGenerator }   from './types-generator.js'
import { Validator }        from './validator.js'
import { AnimationEngine }  from '../gsap/index.js'
import { DepthEngine } from '../depth/index.js'

import fs   from 'node:fs'
import path from 'node:path'

class Mizumi {
  constructor(config = {}) {
    this.config = {
      tokens    : config.tokens     || {},
      patterns  : config.patterns   || {},
      animations: config.animations || {},
      rules     : config.rules      || {}
    }

    // Validate config before doing anything
    this.validator        = new Validator(this.config)
    const validation      = this.validator.validate()
    if (validation.errors.length > 0) {
      console.warn('\n⚠️  Mizumi Validation Warnings:')
      validation.errors.forEach(e => console.warn(`   ${e}`))
      console.warn('')
    }

    this.tokenParser      = new TokenParser(this.config.tokens)
    this.utilityGenerator = new UtilityGenerator(this.config.tokens)
    this.patternExpander  = new PatternExpander(this.config.patterns)
    this.variantGenerator = new VariantGenerator(this.config)
    this.typesGenerator   = new TypesGenerator(this.config)
    this.animationEngine  = new AnimationEngine(
      this.config.animations,
      this.config.tokens
    )
    this.depthEngine = new DepthEngine(this.config.depth || {})
  }

  generateCSS() {
    const rules = this.config.rules
    const css   = [
      '/* ================================================',
      '   Generated by Mizumi 💮',
      '   DO NOT EDIT — edit mizumi.config.js instead',
      '   ================================================ */',
      '',
      '/* ===== TOKENS ===== */',
      this.tokenParser.toCSS(),
      '',
      '/* ===== UTILITIES ===== */',
      this.utilityGenerator.toCSS(),
      '',
      '/* ===== PATTERNS ===== */',
      this.patternExpander.toCSS(),
      '',
      '/* ===== ANIMATION MODIFIERS ===== */',
      this.generateModifierCSS(),
      '',
    ]

    if (rules.responsive) {
      css.push('/* ===== RESPONSIVE VARIANTS ===== */')
      css.push(this.variantGenerator.generateResponsiveCSS(this.patternExpander))
      css.push('')
    }

    if (rules.states !== false) {
      css.push('/* ===== STATE VARIANTS ===== */')
      css.push(this.variantGenerator.generateStateCSS(this.patternExpander))
      css.push('')
    }

    if (rules.darkMode) {
      css.push('/* ===== DARK MODE ===== */')
      css.push(this.variantGenerator.generateDarkModeCSS(this.patternExpander))
      css.push('')
    }

    if (rules.containers) {
      css.push('/* ===== CONTAINER QUERIES ===== */')
      css.push(this.variantGenerator.generateContainerCSS(this.patternExpander))
      css.push('')
    }

    if (rules.print) {
      css.push('/* ===== PRINT ===== */')
      css.push(this.variantGenerator.generatePrintCSS())
      css.push('')
    }

    if (rules.motion) {
      css.push('/* ===== MOTION PREFERENCES ===== */')
      css.push(this.variantGenerator.generateMotionCSS())
      css.push('')
    }

    if (rules.orientation) {
      css.push('/* ===== ORIENTATION ===== */')
      css.push(this.variantGenerator.generateOrientationCSS())
      css.push('')
    }
    
    css.push('/* ===== DEPTH LAYER ===== */')
    css.push(this.depthEngine.generateDepthCSS(this.config.tokens))
    css.push('')

    css.push('/* ===== DIMENSION — 2.5D TILT ===== */')
    css.push(this.depthEngine.generateDimensionCSS())
    css.push('')

    return css.join('\n')
  }

  generateModifierCSS() {
    const lines = []

    ;[100,150,200,300,500,800,1000].forEach(d =>
      lines.push(`.duration-${d} { --mz-duration: ${d/1000}s; }`)
    )
    ;[0,100,150,200,300,500,1000].forEach(d =>
      lines.push(`.delay-${d} { --mz-delay: ${d/1000}s; }`)
    )
    ;['fast','normal','slow','slower'].forEach(n =>
      lines.push(`.duration-${n} { --mz-duration-name: ${n}; }`)
    )
    ;['smooth','bouncy','sharp','back','linear'].forEach(e =>
      lines.push(`.ease-${e} { --mz-ease: ${e}; }`)
    )

    return lines.join('\n')
  }

  generateRuntimeScript() {
    return this.animationEngine.generateRuntimeScript()
  }

  build(outputDir = '.mizumi') {
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true })
    }

    const cssPath = path.join(outputDir, 'mizumi.css')
    const css     = this.generateCSS()
    fs.writeFileSync(cssPath, css)
    console.log(`✅ CSS:     ${cssPath} (${kb(css)} KB)`)

    const jsPath = path.join(outputDir, 'mizumi-runtime.js')
    const js     = this.generateRuntimeScript()
    fs.writeFileSync(jsPath, js)
    console.log(`✅ Runtime: ${jsPath} (${kb(js)} KB)`)
    
    const depthPath = path.join(outputDir, 'mizumi-depth-runtime.js')
    const depthJs   = this.depthEngine.generateRuntimeScript()
    fs.writeFileSync(depthPath, depthJs)
    console.log(`✅ Depth:   ${depthPath} (${kb(depthJs)} KB)`)
    
    const dtsPath = path.join(outputDir, 'mizumi.d.ts')
    const dts     = this.typesGenerator.generateDTS()
    fs.writeFileSync(dtsPath, dts)
    console.log(`✅ Types:   ${dtsPath} (${kb(dts)} KB)`)

    const helpersPath = path.join(outputDir, 'mizumi-helpers.js')
    const helpers     = this.typesGenerator.generateHelpers()
    fs.writeFileSync(helpersPath, helpers)
    console.log(`✅ Helpers: ${helpersPath} (${kb(helpers)} KB)`)

    const metaPath = path.join(outputDir, 'mizumi.meta.json')
    const meta     = JSON.stringify({
      tokens    : this.config.tokens,
      patterns  : this.config.patterns,
      animations: this.config.animations,
      rules     : this.config.rules,
      generated : new Date().toISOString()
    }, null, 2)
    fs.writeFileSync(metaPath, meta)
    console.log(`✅ Meta:    ${metaPath} (${kb(meta)} KB)`)

    return { cssPath, jsPath, dtsPath, helpersPath, metaPath }
  }

  expandClassName(className) {
    return this.patternExpander.expandClasses(className)
  }
}

function kb(str) {
  return (Buffer.byteLength(str) / 1024).toFixed(2)
}

export default Mizumi