import { TokenParser }      from './parser.js'
import { UtilityGenerator } from './utility-generator.js'
import { PatternExpander }  from './pattern-expander.js'
import { VariantGenerator } from './variant-generator.js'
import { TypesGenerator }   from './types-generator.js'
import { AnimationEngine }  from '../gsap/index.js'

import fs   from 'node:fs'
import path from 'node:path'

class Mizumi {
  constructor(config = {}) {
    this.config = {
      tokens    : config.tokens     || {},
      patterns  : config.patterns   || {},
      animations: config.animations || {},
      rules     : config.rules      || {}
    }

    this.tokenParser      = new TokenParser(this.config.tokens)
    this.utilityGenerator = new UtilityGenerator(this.config.tokens)
    this.patternExpander  = new PatternExpander(this.config.patterns)
    this.variantGenerator = new VariantGenerator(this.config)
    this.typesGenerator   = new TypesGenerator(this.config)
    this.animationEngine  = new AnimationEngine(
      this.config.animations,
      this.config.tokens
    )
  }

  generateCSS() {
    const css = [
      '/* Generated by Mizumi 🌊 - edit mizumi.config.js not this file */', '',
      '/* ===== TOKENS ===== */',
      this.tokenParser.toCSS(), '',
      '/* ===== UTILITIES ===== */',
      this.utilityGenerator.toCSS(), '',
      '/* ===== PATTERNS ===== */',
      this.patternExpander.toCSS(), '',
      '/* ===== ANIMATION MODIFIERS ===== */',
      this.generateModifierCSS(), '',
      '/* ===== RESPONSIVE VARIANTS ===== */',
      this.variantGenerator.generateResponsiveCSS(this.patternExpander), '',
      '/* ===== STATE VARIANTS ===== */',
      this.variantGenerator.generateStateCSS(this.patternExpander), '',
    ]

    if (this.config.rules.darkMode) {
      css.push('/* ===== DARK MODE ===== */')
      css.push(this.variantGenerator.generateDarkModeCSS(this.patternExpander))
    }

    return css.join('\n')
  }

  generateModifierCSS() {
    const lines = []

    ;[100,150,200,300,500,800,1000].forEach(d =>
      lines.push(`.duration-${d} { --mz-duration: ${d/1000}s; }`)
    )

    ;[0,100,150,200,300,500,1000].forEach(d =>
      lines.push(`.delay-${d} { --mz-delay: ${d/1000}s; }`)
    )

    ;['fast','normal','slow','slower'].forEach(n =>
      lines.push(`.duration-${n} { --mz-duration-name: ${n}; }`)
    )

    ;['smooth','bouncy','sharp','back','linear'].forEach(e =>
      lines.push(`.ease-${e} { --mz-ease: ${e}; }`)
    )

    return lines.join('\n')
  }

  generateRuntimeScript() {
    return this.animationEngine.generateRuntimeScript()
  }

  build(outputDir = '.mizumi') {
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true })
    }

    const cssPath = path.join(outputDir, 'mizumi.css')
    const css     = this.generateCSS()
    fs.writeFileSync(cssPath, css)
    console.log(`✅ CSS: ${cssPath} (${(Buffer.byteLength(css)/1024).toFixed(2)} KB)`)

    const jsPath = path.join(outputDir, 'mizumi-runtime.js')
    const js     = this.generateRuntimeScript()
    fs.writeFileSync(jsPath, js)
    console.log(`✅ Runtime: ${jsPath} (${(Buffer.byteLength(js)/1024).toFixed(2)} KB)`)

    const dtsPath = path.join(outputDir, 'mizumi.d.ts')
    const dts     = this.typesGenerator.generateDTS()
    fs.writeFileSync(dtsPath, dts)
    console.log(`✅ Types: ${dtsPath} (${(Buffer.byteLength(dts)/1024).toFixed(2)} KB)`)

    const helpersPath = path.join(outputDir, 'mizumi-helpers.js')
    const helpers     = this.typesGenerator.generateHelpers()
    fs.writeFileSync(helpersPath, helpers)
    console.log(`✅ Helpers: ${helpersPath} (${(Buffer.byteLength(helpers)/1024).toFixed(2)} KB)`)

  const metaPath = path.join(outputDir, 'mizumi.meta.json');
  const meta = JSON.stringify({
    tokens: this.config.tokens,
    patterns: this.config.patterns,
    animations: this.config.animations,
    rules: this.config.rules
  }, null, 2);
  fs.writeFileSync(metaPath, meta);
  console.log(`✅ Meta JSON: ${metaPath} (${(Buffer.byteLength(meta)/1024).toFixed(2)} KB)`);

    return { cssPath, jsPath, dtsPath, helpersPath, metaPath, }
  }

  expandClassName(className) {
    return this.patternExpander.expandClasses(className)
  }
}

export default Mizumi
